# Generated by Django 5.1 on 2024-08-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_producto_unidad_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='concepto',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('cantidad_inicial', 'Cantidad Inicial'), ('venta', 'Venta'), ('devolución', 'Devolución'), ('ajuste', 'Ajuste'), ('otro', 'Otro')], max_length=20),
        ),
    ]
