# Generated by Django 5.1 on 2024-08-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_pedido_entregado_venta_saldo_pendiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='saldo_pendiente',
        ),
    ]
